import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            THis is my Portfolio
          </p>
          <div>
            
          </div>
        </div>

        

    
          
      </main>
    </>
  )
}
